#installer docker :
#curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh

#demarrage du daemon :
#sudo systemctl start docker

version: '2'
services:
  mariadb:
    container_name: mariadb
    image: 'jsurf/rpi-mariadb:latest'
    environment:
      - MARIADB_USER=ra_user_suitecrm
      - MARIADB_DATABASE=ra_db_suitecrm
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - '/opt/bitnami/mariadb_data:/bitnami'

  suitecrm:
    container_name: suitecrm
    image: 'rthomas67/rpi-suitecrm:v3'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - SUITECRM_DATABASE_USER=ra_user_suitecrm
      - SUITECRM_DATABASE_NAME=ra_db_suitecrm
      - ALLOW_EMPTY_PASSWORD=yes
      - SUITECRM_USERNAME=_suitecrm_username
      - SUITECRM_PASSWORD=_suitecrm_password
      - SUITECRM_LASTNAME=_suitecrm_lastname
      - SUITECRM_SMTP_HOST=smtp.gmail.com
      - SUITECRM_SMTP_USER=hhoareau@gmail.com
      - SUITECRM_SMTP_PASSWORD=hh4271!!
      - SUITECRM_SMTP_PROTOCOL=TLS
      - SUITECRM_SMTP_PORT=587
      - LETSENCRYPT_HOST=_yourdomain
      - LETSENCRYPT_EMAIL=_youremail
      - VIRTUAL_HOST=_yourdomain
      - VIRTUAL_PORT=80
      - VIRTUAL_NETWORK=nginx-proxy
    volumes:
      - '/opt/bitnami/suitecrm_data:/bitnami'
    depends_on:
      - mariadb
